### ISSUE TITLE
doest support for Windows 10 Enterprise LTSC 2021

### ISSUE THREAD

**Issue by coder4temp** [x0xr00t/Automated-MUlti-UAC-Bypass#10]
in your powershell switch case you dont have this Windows 10 Enterprise LTSC 2021 version. Hence it is not working probably. 

Output:
PS C:\No AV\master\Automated-MUlti-UAC-Bypass-master> .\Win-Multi-UAC-Bypass.ps1

 000000000000000000000000000000000000000000
 0 Sl0ppyR00t Gonna Check the os version. 0
 0      We do the UAC based on the os     0
 0     So that u dont need to check it.   0
 0            Team Sl0ppyRoot             0
 0               ~x0xr00t~                0
 000000000000000000000000000000000000000000

PS C:\No AV\master\Automated-MUlti-UAC-Bypass-master> (get-itemproperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion" -Name ProductName).ProductName
Windows 10 Enterprise LTSC 2021

**Comment by x0xr00t** [comment]
Thanks for the feedback, and also for the issue.
Like i thought and said before, it would likely be due to missing block for LTSC. 
I would say add it to the case check as block. 
i can see later on, if i can make a block for it.
