### ISSUE TITLE
UAC still prompts for admin credentials

### ISSUE THREAD

**Issue by keytrap-x86** [x0xr00t/Automated-MUlti-UAC-Bypass#18]
Hi,

I was trying to test to bypass UAC on a Windows 10 Iot Entreprise 2021 LTSC.

Here are the steps I took :

1. Dowloaded .ps1 & .cs files to c:\tmp
2. Encoded command 'cmd' to base64 and replaced `>b64PayloadHere<` in `sl0puacb.cs` with the base64 value of 'cmd' (I wanted to launch a cmd)
3. Executed Set-ExecutionPolicy Bypass -Scope CurrentUser in powershell
4. cd to C:\tmp and started .ps1 file (as low power local user).

Here's the output :
![Animation](https://github.com/x0xr00t/Automated-MUlti-UAC-Bypass/assets/17864005/b7815afb-b146-4245-aeb2-ef2d8261ae1f)

![image](https://github.com/x0xr00t/Automated-MUlti-UAC-Bypass/assets/17864005/ec605fed-574b-4514-8f0f-8828671590db)

Did I understand everything correctly or did I make a mistake ?
Also, I don't understand how the script is supposed to copy sl0p.dll to c:\windows\xxx if it hasn't got the admin rights ?

**Comment by x0xr00t** [comment]
Hello, sir. Can you tell me the following ? 
Did u use the new source, or the backup files ? 
In both cases its needed to edit the .ps1 and .cs with the dirs and users information. 
This needs to be done before hand of rolling out the new .cs file for the new source. 
And if used the old source from the backup folder, it needs to be in the same folder dirs as in the script .ps1 else it cant load the dll to place the files in the mock folder of C:\windows .. 

So recheck and edit the paths where needed and change the user where needed. 
If u still encounter issues after changing all that, let me know and i will make a vm to test it myself.

**Comment by keytrap-x86** [comment]
I have download the repo as a zip and extracted the contents.
Changed the command un the cs file and my username in the ps1 file, but still the same : access denied when copying the sl0p.dll in C:\Windows...

![noice](https://github.com/x0xr00t/Automated-MUlti-UAC-Bypass/assets/17864005/435e4167-70ef-4b3e-85eb-1e05964ad5da)

Maybe you could make a little video from A to Z just to be sure I don't miss any steps?

**Comment by x0xr00t** [comment]
Hello sir, thanks for the feedback. 
I noticed there is a issue compiling the dll, i am working on solving the issue and release a new release once its fixed.. stay tuned for the new release.

**Comment by x0xr00t** [comment]
The compile issue is sorted, i will close the issue and push new release. 
Thanks for your time, and notifying me on this issue. 

Kinds, 
x0xr00t
