### ISSUE TITLE
1.5.6-beta not working yet

### ISSUE THREAD

**Issue by keytrap-x86** [x0xr00t/Automated-MUlti-UAC-Bypass#21]
Please see the video
https://i.imgur.com/0aBAPJG.mp4

**Comment by x0xr00t** [comment]
I just re-uploaded the older dll file, and the older .cs. 
I tested it and its working, so re-download the package and retest please.

**Comment by x0xr00t** [comment]
dont open the .cs and edit it. just run the .ps1 without edit the .cs
