### ISSUE TITLE
Not working even with a fresh install

### ISSUE THREAD

**Issue by keytrap-x86** [x0xr00t/Automated-MUlti-UAC-Bypass#22]
I have tried with a Windows 10 Professional 22H2 (latest iso downloaded from Microsoft) and still the same problem :
This time I just downloaded the zip and ran the powershell.

https://i.imgur.com/0DUsTns.mp4

**Comment by keytrap-x86** [comment]
It only works if I unput admin logins of course

![Animation](https://github.com/x0xr00t/Automated-MUlti-UAC-Bypass/assets/17864005/5d9e3fd4-9962-4098-96b8-f25bafb3878e)

Are you sure that you test this with a low power user and that the admin account has a password ?

**Comment by x0xr00t** [comment]
U can't run it from low user. 

Have a look here: 
https://book.hacktricks.xyz/windows-hardening/authentication-credentials-uac-and-efs/uac-user-account-control

**Comment by keytrap-x86** [comment]
> U can't run it from low user.
> 
> Have a look here: https://book.hacktricks.xyz/windows-hardening/authentication-credentials-uac-and-efs/uac-user-account-control
> 
> In the section check UAC it explains all bout the levels 0-5.
> 
> U can't run it from a low user, to get administrator access without knowing the administrator pw.

Ok si this bypasses only when already admin ?

**Comment by x0xr00t** [comment]
correct, it will bypass the prompt to verify to exec stuff when admin. 
U could lower it to 0 to disable it complete for all users, with dword.

![Screenshot 2023-11-30 at 12-09-46 UAC - User Account Control - HackTricks](https://github.com/x0xr00t/Automated-MUlti-UAC-Bypass/assets/25748471/7d2522a9-4eed-4d6e-9149-bdbc5f9f81d4)

-

**Comment by x0xr00t** [comment]
@keytrap-x86 for nullifying the LUA settings u can use this tool, that i also wrote. 
https://github.com/x0xr00t/sl0ppy-Nullify-LUA
