### ISSUE TITLE
Serious issues

### ISSUE THREAD

**Issue by Miracles666** [x0xr00t/Automated-MUlti-UAC-Bypass#26]
After running the modification script, all the shortcut settings on my computer (such as personalization and display settings) became CMD pop ups, and I don't know how to restore them

**Comment by x0xr00t** [comment]
@Miracles666 which version did u run the latest ??

**Comment by Miracles666** [comment]
yes   i was run the latest 
OS Name: Microsoft Windows 10 Professional Edition

OS version: 10.0.19045, Build 19045 is currently missing

**Comment by x0xr00t** [comment]
i will have a look after the weekend.
