### ISSUE TITLE
After execution, 2 windows files appeared on my computer.

### ISSUE THREAD

**Issue by letmejustdoit** [x0xr00t/Automated-MUlti-UAC-Bypass#27]
After execution, 2 windows files appeared on my computer.

2022/05/07 13:24 <DIR> PerfLogs
2024/01/25 18:49 <DIR> PROGRA~1 Program Files
2023/12/27 16:46 <DIR> PROGRA~2 Program Files (x86)
2023/06/08 19:57 <DIR> TORBRO~1 Tor Browser
2023/06/08 14:25 <DIR> Users
2024/01/26 10:31 <DIR> Windows
2024/01/19 15:04 <DIR> WINDOW~1 Windows

I don't know how to handle this now. This folder is also too scared to delete. Don't know how to do it. Can you tell me how to solve this problem?

**Comment by letmejustdoit** [comment]
C:\WINDOW~1 的目录

2024/01/19  15:04    <DIR>          .
2024/01/25  18:55    <DIR>          ..
2024/01/19  15:04    <DIR>          System32
               0 个文件              0 字节
               3 个目录 179,839,770,624 可用字节

C:\WINDOW~1>dir /x
 驱动器 C 中的卷是 Win
 卷的序列号是 329C-2A72

 C:\WINDOW~1 的目录

2024/01/19  15:04    <DIR>                       .
2024/01/19  15:04    <DIR>                       System32

**Comment by x0xr00t** [comment]
new release been pushed
