### ISSUE TITLE
Am i stupid or does this UAC bypass not bypass UAC?

### ISSUE THREAD

**Issue by mastercodeon314** [x0xr00t/Automated-MUlti-UAC-Bypass#29]
I have thoroughly reviewed this repo, and i really don't understand where the UAC bypass is executed. I see the code that is in the .cs file and the .net dll file that has the UAC bypass, but what in the world calls it?
The ps1 script just sets it up. I converted the dll into an exe and executed it, but still no popping of an elevated cmd. 
What am i missing here?

**Comment by x0xr00t** [comment]
Hello, i dont get why you convert the DLL to an are it's not needed at all. Besides  that it works if u just follow the reader.md. there for i suguest to read te info on the readme.md, and follow the instructions. There for i will close this issue as it is not a code issue.
