### ISSUE TITLE
I can't get the code to work

### ISSUE THREAD

**Issue by sh3ll4rpw** [x0xr00t/Automated-MUlti-UAC-Bypass#3]
OS; Windows 10 pro build 19044
First i've ran "Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope CurrentUser"
After that I put I all the files together. When I run the script with powershell I only get this output in terminal:
`
$ C:\Users\user\Downloads\Automated-MUlti-UAC-Bypass-master>powershell -noexit -executionpolicy bypass -command ".\Win-Multi-UAC-Bypass.ps1"

 000000000000000000000000000000000000000000
 0 Sl0ppyR00t Gonna Check the os version. 0
 0      We do the UAC based on the os     0
 0     So that u dont need to check it.   0
 0            Team Sl0ppyRoot             0
 0               ~x0xr00t~                0
 000000000000000000000000000000000000000000

$ PS C:\Users\user\Downloads\Automated-MUlti-UAC-Bypass-master>
`

Nothing else happens. But there are no errors. As you see I other 'Write Host" text is missing so it seems to stop running. I didn't touch the code at all. I tried to .exe too. Same problem. how to solve this?

**Comment by x0xr00t** [comment]
Can you please provide the next info 

The user u ran as ?  admin or low lever user ..
Check if defender defender tamper is disabled

**Comment by sh3ll4rpw** [comment]
Low level user. Yes tamper is enable. That might be the case thank you

**Comment by x0xr00t** [comment]
I will close the issue for now, if u stumble on any issue's your free to make new one. 
Thanks
