### ISSUE TITLE
sl0p.dll

### ISSUE THREAD

**Issue by sec13b** [x0xr00t/Automated-MUlti-UAC-Bypass#37]
![image](https://github.com/user-attachments/assets/0a92ca00-bb4d-4cc4-8a48-01aa2e19358a)

**Comment by x0xr00t** [comment]
Oh my bad not the .cs the .ps1 its in

**Comment by x0xr00t** [comment]
pushed a update, let me know.

**Comment by x0xr00t** [comment]
i will test it later on when i can, but i dont have vps at hands or vms to test. 
i will dive in to it, but would be faster if you could send me a ss. 
me quite limited on resources so can't really test it as of now.
