### ISSUE TITLE
Only title is shown

### ISSUE THREAD

**Issue by coder4temp** [x0xr00t/Automated-MUlti-UAC-Bypass#9]
000000000000000000000000000000000000000000
 0 Sl0ppyR00t Gonna Check the os version. 0
 0      We do the UAC based on the os     0
 0     So that u dont need to check it.   0
 0            Team Sl0ppyRoot             0
 0               ~x0xr00t~                0
 000000000000000000000000000000000000000000

nothing else upon loading the powershell script on windows 10 enterprise ltsc
powershell -ep bypass 
.\uacbypass.ps1

**Comment by x0xr00t** [comment]
Check if all version names, build names are correct in the script. 
Check if powershell is preventing it from running it. 
Check if virus & thread protection is enabled, it needs to be disabled temp.
Make sure the dll is still in the folder, else re-make it with powershell command.
